# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: stacks 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "stacks"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Huie"]
  s.date = "2013-12-14"
  s.description = "Fancy redis-backed caches"
  s.email = "david@nationbuilder.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/stacks.rb",
    "lib/stacks/backends/backend.rb",
    "lib/stacks/backends/key_value_backend.rb",
    "lib/stacks/backends/namespaced_backend.rb",
    "lib/stacks/cache.rb",
    "lib/stacks/column_dependent_cache.rb",
    "lib/stacks/items/column_dependent_block.rb",
    "lib/stacks/items/method_call.rb",
    "lib/stacks/items/proc.rb",
    "lib/stacks/items/timestamp.rb",
    "lib/stacks/method_cache.rb",
    "lib/stacks/model_extensions.rb",
    "lib/stacks/report_cache.rb",
    "spec/backends/backend_spec.rb",
    "spec/backends/key_value_backend_spec.rb",
    "spec/backends/namespaced_backend_spec.rb",
    "spec/column_dependent_cache_spec.rb",
    "spec/items/column_dependent_block_spec.rb",
    "spec/items/method_call_spec.rb",
    "spec/items/proc_spec.rb",
    "spec/method_cache_spec.rb",
    "spec/model_extensions_spec.rb",
    "spec/report_cache_spec.rb",
    "spec/spec_helper.rb",
    "stacks.gemspec"
  ]
  s.homepage = "http://github.com/3dna/stacks"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Fancy redis-backed caches"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<mock_redis>, ["~> 0.10.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.8.2"])
      s.add_development_dependency(%q<sqlite3>, ["~> 1.3.8"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<pry>, ["~> 0.9.12.4"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<mock_redis>, ["~> 0.10.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.8.2"])
      s.add_dependency(%q<sqlite3>, ["~> 1.3.8"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<pry>, ["~> 0.9.12.4"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<mock_redis>, ["~> 0.10.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.8.2"])
    s.add_dependency(%q<sqlite3>, ["~> 1.3.8"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<pry>, ["~> 0.9.12.4"])
  end
end

